### ISSUE TITLE
GAS-080 Google Form with UID in Confirmation | TypeError: Cannot read property 'range' of undefined with run(e) AND _onFormSubmit Event

### ISSUE THREAD

**Issue by testLPCP** [ashtonfei/google-apps-script-projects#1]
TypeError: Cannot read property 'range' of undefined
run	@ Code.gs:56
_onFormSubmit	@ Code.gs:65

in short issue with run(e) AND _onFormSubmit Event

New Form Created [Google Form with UID in Confirmation](https://docs.google.com/forms/d/1Gn4Ud3uzjbf9jigGBIXwUEvAerQaELHyFhX3CfCWJVE/edit#settings)

On [Form submission](https://docs.google.com/forms/u/0/d/e/1FAIpQLSfjpH0Gf_R8sNLy_zUA482Z0KmP2wgik8CpH3ljC9i7W4ZZag/formResponse) the records are saved to GoogleSheet (downloaded & copied from your site) [Google Form with UID in Confirmation](https://docs.google.com/spreadsheets/d/1PX7SPLwbl7rtVkTMXUFC6inae7A-mPij4wehgP9z_I4/edit#gid=1575888123)  

We checked and found that the Google Form copies and customized as above after verifying to the SENd FORM with the selected above link still linked with [Your Template Form](https://docs.google.com/forms/d/e/1FAIpQLSfjpH0Gf_R8sNLy_zUA482Z0KmP2wgik8CpH3ljC9i7W4ZZag/viewform?usp=sf_link) and not our linked form.

However the data is posted to our customized linked Spreadsheet, with new sheet (Response 2 | 3 | 4 different try) within the spreadsheet and not to the (newly created sheet) of the **this.ss**, but no UID is added to the post. Now the option to configure the post the records to such sheet from linking is by default send to your sheet of your sheet Response template and not newly created by app to Response 2 ... 

How can we change the post from this.ss (Response) to this.ss (Response 2) where the post is submitted, but the UID is not automated. Need to resolve the two Response sheet conflicting 'this.ss' of posting of records onSubmitEvent, so that the submission is posted either of the logical SpreadSheet to store & retrieve the data

Forwarded the both sheet link above in shared with public access for time being, and please to fix the deployed project not working.

https://docs.google.com/forms/d/1Gn4Ud3uzjbf9jigGBIXwUEvAerQaELHyFhX3CfCWJVE/edit#question=226269182&field=1849531307
https://docs.google.com/spreadsheets/d/1PX7SPLwbl7rtVkTMXUFC6inae7A-mPij4wehgP9z_I4/edit#gid=1575888123

**Comment by ashtonfei** [comment]
The event (e) object in the function can't only be assigned when the function is triggered by the form submission event. You can't run the function manually, or the event is undefined and you'll see the "XXX of undefined error".

And I tested your form, it's working now.
![image](https://user-images.githubusercontent.com/16481229/135788698-e9f57450-e1d8-42e6-a172-f9a6fea551da.png)

![image](https://user-images.githubusercontent.com/16481229/135788566-930f2bc5-9042-4c03-a65b-27a4f3faa7a5.png)

When the function is executed by the trigger or by yourself manually.
![image](https://user-images.githubusercontent.com/16481229/135789090-50b8ae69-03dd-4c80-9b54-461e4e14021b.png)

**Comment by pyisoemin** [comment]
Hello, Mr. Ashtonfei
Could you please update code request to you, I would like to show the "UID-XXXXX" (e.g. "UID-00001") in email notification Subject?
Thanks
